### ISSUE TITLE
Batch downloader failing using pclzip and php 7.1

### ISSUE THREAD

**Issue by tjw1184** [mistic100/Piwigo-BatchDownloader#18]
Receiving following php error:

Notice: A non well formed numeric value encountered in /config/www/gallery/admin/include/pclzip.lib.php on line 1845

After a little googling, it appears that the issue is related to requiring the memory_limit needing to get casted correctly in php 7.1.   Possible solutions:

https://github.com/piwik/component-decompress/pull/9
https://github.com/FineUploader/php-traditional-server/pull/17

Batch Downloader: 2.2.3
Environment
PHP 7.1.5
PclZip 2.8.2

**Comment by mistic100** [comment]
pclzip is packaged with the main Piwigo code, please submit the issue here https://github.com/Piwigo/Piwigo
