### ISSUE TITLE
Bring theme compatibility to bootstrap*

### ISSUE THREAD

**Issue by petitssuisses** [mistic100/Piwigo-BatchDownloader#19]
Plugin is currently not compatible with bootstrap themes (bootstrap_darkroom, bootstrapdefault). BatchDownloader menu breaks the existing menu layout.

**Comment by plegall** [comment]
bootstrap_darkroom is compatible today, can you confirm @tkuther

**Comment by petitssuisses** [comment]
Confirmed, I close. Thanks
