### ISSUE TITLE
Anyway to download more than 500?

### ISSUE THREAD

**Issue by Elliot-Potts** [mistic100/Piwigo-BatchDownloader#20]
Hello, 

I was just wondering if there's any way to download greater than 500 images at a time without having to edit a set.

I noticed there's a value in BatchDownloader/admin/config.php...

Anyway,
Thanks.

**Comment by mistic100** [comment]
In your local config file (using Local Files Editor)

```php
$conf['batch_download_max_size'] = whatever;
```

That's the purpose of the `isset` in the page you found.

**Comment by mistic100** [comment]
And I think it is described in the config page itself when clicking Advanced features -> Display

**Comment by Elliot-Potts** [comment]
Ahh.

Didn't use the local files editor.

My apologies for wasting your time. 
I love your plugin by the way, just what I was looking for.

Thanks again.
