### ISSUE TITLE
Some files may have been excluded because of filetype restrictions.

### ISSUE THREAD

**Issue by demichej** [mistic100/Piwigo-BatchDownloader#3]
Hello, I am getting an error that I don't know how to get around to download an album. Here's the wording:

"Sorry, there is nothing to download. Some files may have been excluded because of filetype restrictions."

Any help would be appreciated. Some albums download fine and some do not. Thanks.

**Comment by mistic100** [comment]
Hi

Gallery link ?

the plugin is only able to process JPEG, PNG and GIF

**Comment by demichej** [comment]
Hey, thanks for the response. Not sure if this is a "bug" or not, but it looks like the data you are using from the database (at least in my case) isn't the right field to use. It looks like you are using "file" to select from the DB. BatchDownloader around line 215......but in my case it appears the "path" is the correct data to use. Here's the data in the database:

```mysql> select * from piwigo_images where id=531\G
*************************** 1. row ***************************
                  id: 531
                file: 1527
      date_available: 2013-06-22 13:46:00
       date_creation: NULL
                name: IPH0009
             comment: NULL
              author: NULL
                 hit: 11
            filesize: 1861
               width: 3264
              height: 1808
                 coi: NULL
  representative_ext: NULL
date_metadata_update: 2013-06-22
        rating_score: NULL
                path: ./upload/2013/06/22/20130622134600-eab28c9b.jpg
```

I changed the code locally to use "path" and all is good now. Thanks.

**Comment by mistic100** [comment]
don't know how but your database is corrupted, there should be an extension in the `file` column.

I suggest you write an SQL query to append the extension from `path` when it's missing in `file`
