### ISSUE TITLE
not compatible with 2.7

### ISSUE THREAD

**Issue by awikatchikaen** [mistic100/Piwigo-BatchDownloader#4]
I have this error whenever i try to download an album.

Fatal error: Call to undefined function trigger_event() in /.../piwigo/plugins/BatchDownloader/include/functions.inc.php on line 72

**Comment by mistic100** [comment]
You should try to update it.
The last version (2.2.2) totally works.

**Comment by awikatchikaen** [comment]
ho sorry. Didn't see that the plugin was on "ignore update" list. 
I Confirm it works with the last version.

Thank you
