### ISSUE TITLE
Problem with httpd

### ISSUE THREAD

**Issue by mfrey777** [mistic100/Piwigo-BatchDownloader#5]
Hello,

I have installed the BatchDownloader 2.2.2 on my website with Piwigo 2.8.1

I get an error message when clicking on the download link, after I select the image size.

The download is generating the following URL (which looks correct) https://www.freyonline.net/gallery/index.php?/category/7&action=advdown_set&down_size=square

The problem is that on the next page the URL is: https://freyonline.net:80/gallery/index.php?/download/init_zip&set_id=8

https and port 80 does not work. The link works if I manually do one of the 3 actions:
- Change port number to 443
- Remove the port number
- Change https to http

I did not find any setting to control the port number, can you please fix this issue ?

**Comment by mistic100** [comment]
Hi

I'm only using core methods to generate the URL and redirect
https://github.com/mistic100/Piwigo-BatchDownloader/blob/master/include/events.inc.php#L114
https://github.com/mistic100/Piwigo-BatchDownloader/blob/master/main.inc.php#L32

I guess there is a bug in `get_absolute_root_url`. Please submit the issue in Piwigo repository.

**Comment by mfrey777** [comment]
Hi, 

Thank you for the quick and detailed feed-back, I will submit the issue in the Piwigi repository
